### ISSUE TITLE
Conditional check

### ISSUE THREAD

**Issue by mortensassi** [ooksanen/acf-focuspoint#10]
I'm using wordplate/acf-extended and writing something like this:

```php

        ->conditionalLogic([
            ConditionalLogic::if('image')->notEmpty()
        ]),
 ```

does not work - does not get recognized - Any idea how to check if this field is populated?

**Comment by ooksanen** [comment]
Hi and sorry for late reply!

I'm not familiar with WordPlate or Extended ACF but at the moment you can check if image id is set to check for focuspoint image. 

I'll probably try to make the field work a bit differently at some point to enable conditional logic for the whole field like in your example, but it's not a very high priority for me at the moment as the check for image id works ok for me.
