### ISSUE TITLE
Compatibility with Elementor

### ISSUE THREAD

**Issue by henry-parkside** [ooksanen/acf-focuspoint#11]
Hi there, I use Elementor page builder, and the regular ACF Image fields show up fine.

This addon would solve a lot of the problems on our blogging site, so was just wondering if there would be support for it to work with Elementor.

I believe it just needs to be recognised as an image field... somehow.

Thanks,
Henry

**Comment by henry-parkside** [comment]
Hi Oskari,

Thanks so much for your prompt response. Completely understand that it's working for you as is and you can't promise anything.

This is a major feature missing from Elementor, no idea why they haven't considered it yet... I've got a recording here that shows you how their UI displays ACF fields. I think you are correct in saying that it only identifies default fields, so would there be a way of making FocusPoint identify as an image field?

Not experienced in JS/PHP sorry, so I'm not much help there!

Also, I don't believe we have utilised any other custom ACF fields.

Thanks again,
Henry

https://user-images.githubusercontent.com/87354183/125538434-585a0355-06f2-4b6c-b8a3-cd93c9d5ee51.mp4

**Comment by ooksanen** [comment]
Yeah, I took a quick look at Elementor's documentation on ACF integration (https://elementor.com/help/elementor-acf/) and indeed they only seem support a certain set of ACF fields (not even all the default ones) so unfortunately there's really not much I can do. Hope you can find another solution!

**Comment by henry-parkside** [comment]
Ok, no worries. Thanks for looking into it anyway! All the best, Henry.
