### ISSUE TITLE
Why is the plugin marked as Must-use?

### ISSUE THREAD

**Issue by avioli** [ooksanen/acf-focuspoint#15]
https://github.com/ooksanen/acf-focuspoint/blob/8b8b361dd94443257c19c3372fca8bc864909ba6/composer.json#L4

Can this be changed to `"type": "wordpress-plugin"`?

**Comment by ooksanen** [comment]
Sure! To be honest, I didn't even notice it was marked as mu-plugin when I merged a pull request that added composer support. If you don't use composer, you can jusrt download the files and use this as a regular plugin.
