### ISSUE TITLE
Required Image not working

### ISSUE THREAD

**Issue by timbowen** [ooksanen/acf-focuspoint#6]
These recent updates you've made are fantastic and the plugin is working so well now! The only issue I'm seeing is the "Required?" box for the FocusPoint image does not seem to work: https://cs.zone/F9mfAR

If you check that box, you can see still save the page, even without adding an an image:
https://cs.zone/qX5wM7

Here's how it works for other required fields:
https://cs.zone/TJXxZ5

Let me know if you need any help troubleshooting this. Thank you!

**Comment by ooksanen** [comment]
Fixed in 1.1.3.

Please note that validation doesn't work in Gutenberg at the moment. See https://github.com/AdvancedCustomFields/acf/issues/113 for more info.

**Comment by ooksanen** [comment]
Clarification: The validation doesn't work for ACF Blocks, but should work for meta boxes.

**Comment by timbowen** [comment]
You are incredible. Thank you!
