### ISSUE TITLE
Field returns array with empty id when image gets deleted

### ISSUE THREAD

**Issue by DenisLanz** [ooksanen/acf-focuspoint#8]
The field returns an array with the coordinates but without an image id. I would appreciate if the field aligns to the standard behaviour of the acf fields and return `false` if there is no image. This would make it easier to check for an empty field like 
```php
if ( get_field() ) {}
```

**Comment by timbowen** [comment]
Agreed Denis, that would be ideal. However we used this workaround which works in the meantime:
`$focus_point = get_field('focus_point')
if ( !empty($focus_point['id']) ) {`

**Comment by DenisLanz** [comment]
Yeah. I wrapped it into a function to avoid writing the check every time - still would appreciate if it is a part of the plugin.

**Comment by ooksanen** [comment]
Fixed in 1.1.5
