### ISSUE TITLE
Limit Library Upload Choices

### ISSUE THREAD

**Issue by DenisLanz** [ooksanen/acf-focuspoint#9]
Me again ;) This is just a feature request. I just realised that I can't, as by the default image field, add a Library limit to limit the user to images uploaded to the current post.

**Comment by ooksanen** [comment]
Thanks for the suggestion! I'll see what I can do at some stage, but honestly this is not very high on my priority list at the moment.

**Comment by DenisLanz** [comment]
Thought so, not crucial, just stumbled over it.

**Comment by ooksanen** [comment]
Hi @DenisLanz,

I've just updated the plugin with options for Library (All / Uploaded to post) and also Allowed file types.
